version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r app/requirements.txt
      